# Generated by Django 2.2.5 on 2019-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_Name', models.CharField(max_length=200)),
                ('Medicine_Type', models.CharField(max_length=200)),
                ('Medicine_Mg', models.IntegerField()),
                ('Medicine_Expiriy_Date', models.CharField(max_length=200)),
                ('Medicine_Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_Name', models.CharField(max_length=200)),
                ('Patient_Address', models.CharField(max_length=200)),
                ('Patient_Phone_Number', models.CharField(max_length=200)),
                ('Patient_Age', models.CharField(max_length=200)),
                ('Patient_Diseases', models.TextField(max_length=200)),
                ('Patient_Rx', models.CharField(blank=True, choices=[('Renava', 'Renava'), ('napa', 'napa'), ('opton', 'opton'), ('ctz', 'ctz')], max_length=40, null=True)),
                ('Medicine_Morning', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provided_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.CharField(max_length=200)),
                ('Patient_Name', models.CharField(max_length=200)),
                ('Patient_Address', models.CharField(max_length=200)),
                ('Provided_Medicine', models.TextField(max_length=200)),
            ],
        ),
    ]
