# Generated by Django 2.2.5 on 2019-11-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191128_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Days',
        ),
    ]
