# Generated by Django 2.2.5 on 2019-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191129_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Medicine_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='Medicine_noon',
            field=models.BooleanField(default=False),
        ),
    ]
