# Generated by Django 2.2.5 on 2019-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191129_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Total_Medicine',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
