# Generated by Django 2.2.5 on 2019-11-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_patient_provided_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Per_day',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Provided_Medicine',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Total_medicine',
        ),
    ]
