# Generated by Django 2.2.5 on 2019-11-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20191129_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Per_day',
            field=models.CharField(default=20, max_length=200),
            preserve_default=False,
        ),
    ]
