# Generated by Django 2.2.5 on 2019-11-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_patient_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Total_medicine',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
