# Generated by Django 2.2.5 on 2019-11-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_patient_total_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Total_medicine',
            field=models.CharField(max_length=200),
        ),
    ]
