# Generated by Django 2.2.5 on 2019-11-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
