# Generated by Django 2.2.5 on 2019-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='give_medi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_Name', models.CharField(max_length=200)),
                ('Medicine_Type', models.CharField(max_length=200)),
                ('Medicine_Mg', models.IntegerField()),
                ('Medicine_Expiriy_Date', models.CharField(max_length=200)),
                ('Medicine_Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Information',
            fields=[
                ('Patient_ID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Patient_Name', models.CharField(max_length=200)),
                ('Patient_Address', models.CharField(max_length=200)),
                ('Patient_Phone_Number', models.CharField(max_length=200)),
                ('Patient_Age', models.CharField(max_length=200)),
                ('Patient_Diseases', models.TextField(max_length=200)),
            ],
        ),
    ]
