# Generated by Django 2.2.5 on 2019-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='give_medi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_Name', models.CharField(max_length=200)),
                ('Medicine_Type', models.CharField(max_length=200)),
                ('Medicine_Mg', models.IntegerField()),
                ('Medicine_Expiriy_Date', models.CharField(max_length=200)),
                ('Medicine_Quantity', models.IntegerField()),
            ],
        ),
    ]
