# Generated by Django 2.2.5 on 2019-10-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.IntegerField()),
                ('Patient_Name', models.CharField(max_length=200)),
                ('Patient_Age', models.CharField(max_length=200)),
                ('Patient_Precribed', models.TextField(max_length=200)),
            ],
        ),
    ]
