# Generated by Django 2.2.5 on 2019-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='doctor_name',
            new_name='user',
        ),
    ]
