# Generated by Django 2.2.5 on 2019-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20191130_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_name',
            field=models.CharField(default='prashantasaha', max_length=200),
            preserve_default=False,
        ),
    ]
